# coding: utf-8

"""
    Gurobi Remote Services API

    The Gurobi Remote Services is used to control a compute  node  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from grb_rs_monitor.api_client.swagger_client.configuration import Configuration


class ConfigUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_limit': 'int'
    }

    attribute_map = {
        'job_limit': 'jobLimit'
    }

    def __init__(self, job_limit=None, _configuration=None):  # noqa: E501
        """ConfigUpdate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._job_limit = None
        self.discriminator = None

        if job_limit is not None:
            self.job_limit = job_limit

    @property
    def job_limit(self):
        """Gets the job_limit of this ConfigUpdate.  # noqa: E501

        New job limit  # noqa: E501

        :return: The job_limit of this ConfigUpdate.  # noqa: E501
        :rtype: int
        """
        return self._job_limit

    @job_limit.setter
    def job_limit(self, job_limit):
        """Sets the job_limit of this ConfigUpdate.

        New job limit  # noqa: E501

        :param job_limit: The job_limit of this ConfigUpdate.  # noqa: E501
        :type: int
        """

        self._job_limit = job_limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConfigUpdate):
            return True

        return self.to_dict() != other.to_dict()
