# coding: utf-8

"""
    Gurobi Remote Services API

    The Gurobi Remote Services is used to control a compute  node  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from grb_rs_monitor.api_client.swagger_client.configuration import Configuration


class ValidationMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'param': 'str',
        'msg': 'str',
        'value': 'str'
    }

    attribute_map = {
        'param': 'param',
        'msg': 'msg',
        'value': 'value'
    }

    def __init__(self, param=None, msg=None, value=None, _configuration=None):  # noqa: E501
        """ValidationMessage - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._param = None
        self._msg = None
        self._value = None
        self.discriminator = None

        if param is not None:
            self.param = param
        if msg is not None:
            self.msg = msg
        if value is not None:
            self.value = value

    @property
    def param(self):
        """Gets the param of this ValidationMessage.  # noqa: E501

        the input field that failed validation  # noqa: E501

        :return: The param of this ValidationMessage.  # noqa: E501
        :rtype: str
        """
        return self._param

    @param.setter
    def param(self, param):
        """Sets the param of this ValidationMessage.

        the input field that failed validation  # noqa: E501

        :param param: The param of this ValidationMessage.  # noqa: E501
        :type: str
        """

        self._param = param

    @property
    def msg(self):
        """Gets the msg of this ValidationMessage.  # noqa: E501

        the validation error message  # noqa: E501

        :return: The msg of this ValidationMessage.  # noqa: E501
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this ValidationMessage.

        the validation error message  # noqa: E501

        :param msg: The msg of this ValidationMessage.  # noqa: E501
        :type: str
        """

        self._msg = msg

    @property
    def value(self):
        """Gets the value of this ValidationMessage.  # noqa: E501

        the received value  # noqa: E501

        :return: The value of this ValidationMessage.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ValidationMessage.

        the received value  # noqa: E501

        :param value: The value of this ValidationMessage.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidationMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidationMessage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ValidationMessage):
            return True

        return self.to_dict() != other.to_dict()
